### ISSUE TITLE
Incorrect repo URL in README

### ISSUE THREAD

**Issue by hudson155** [skeleton-scaffolding/skeleton#17]
The README says I should clone from
```
https://github.com/AndrewMcBurney/skeleton.git
```

I want to clone from
```
https://github.com/skeleton-scaffolding/skeleton.git
```

**Comment by AndrewMcBurney** [comment]
You can still clone from the old repo despite git clone https://github.com/AndrewMcBurney/skeleton.git ~/tem

**Comment by AndrewMcBurney** [comment]
Hey Jeff, thank you for letting me know about the `README.md`. I just updated the file - so I'm going to close the issue. Cheers 🍻

**Comment by hudson155** [comment]
![image](https://user-images.githubusercontent.com/1360420/27066261-968afc74-4fb7-11e7-9fe3-95ec03fcf4a3.png)
